import { prisma } from '../db/prisma.js';
import { generateDidKey } from './generateDid.js';
import { NotFoundError } from '../errors.js';

// Creates a new did:key identity and persists it. Used for both issuer and
// holder identities in Phase 1 — the DID generation process is identical for
// either role, only how they're subsequently used differs.
export async function createAndStoreDidKey() {
  const generated = await generateDidKey();

  return prisma.didKey.create({
    data: {
      did: generated.did,
      verificationMethodId: generated.verificationMethodId,
      publicKeyMultibase: generated.publicKeyMultibase,
      privateKeyMultibase: generated.privateKeyMultibase,
    },
  });
}

export async function getDidKeyByDid(did: string) {
  const didKey = await prisma.didKey.findUnique({ where: { did } });
  if (!didKey) {
    throw new NotFoundError(`DID "${did}" was not generated by this service`, { did });
  }
  return didKey;
}
